@base_url = http://localhost:8000/api
@ACCESS = 
@REFRESH = 

### Login (obtain JWT)

POST {{base_url}}/token/
Content-Type: application/json

[
  {"email": "joachimtramper@gmail.com"},
  {"password": ""}
  ]

> {% client.global.set("ACCESS", response.body.access) %}
> {% client.global.set("REFRESH", response.body.refresh) %}

### Refresh token
POST {{base_url}}/token/refresh/
Content-Type: application/json

{
  "refresh": "{{REFRESH}}"
}

# ADDRESSES -----------------------------------------------------------------------------------

### List my addresses
GET {{base_url}}/users/addresses/
Authorization: Bearer {{ACCESS}}

### Create an address
POST {{base_url}}/users/addresses/
Content-Type: application/json
Authorization: Bearer {{ACCESS}}

{
  "label": "Home",
  "street": "Maple Street",
  "number": "12A",
  "zipcode": "12345",
  "city": "Springfield",
  "country": "USA",
  "is_billing": false,
  "is_shipping": true
}

### PROFILE -----------------------------------------------------------------------------------

### Get my profile
GET {{base_url}}/users/profile/
Authorization: Bearer {{ACCESS}}

### Update my profile
PUT {{base_url}}/users/profile/
Content-Type: application/json
Authorization: Bearer {{ACCESS}}

{
  "phone_number": "+31612345678",
  "date_of_birth": "1990-01-01"
}
