# Generated by Django 5.2 on 2025-06-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_historicaladdress_historicalcustomerprofile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="historicalcustomerprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
