version: 2

secret:
  ignored_paths:
    - "**/tests/**"

    - "**/*.json"

    - ".github/workflows/**"

    - "db.sqlite3"

    - "staticfiles/**"
    - "docs/swagger-ui/**"

    - "conftest.py"

    - "fixtures/*.json.bak"
