version: "3.9"

services:
  web:
    build: .
    command: gunicorn ecommerce_api.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      - DEBUG=True
      - DJANGO_SECRET_KEY=devkey
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_URL=postgres://myuser:mypass@db:5432/ecommerce

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  celery:
    build: .
    command: celery -A ecommerce_api worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_URL=postgres://myuser:mypass@db:5432/ecommerce

  beat:
    build:
      context: .
    command: celery -A ecommerce_api beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
      - db
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_URL=postgres://myuser:mypass@db:5432/ecommerce

volumes:
  postgres_data:
# version: "3.9"

# services:
#   web:
#     build: .
#     command: gunicorn ecommerce_api.wsgi:application --bind 0.0.0.0:8000
#     volumes:
#       - .:/app
#     ports:
#       - "8000:8000"
#     depends_on:
#       - redis
#     environment:
#       - CELERY_BROKER_URL=redis://redis:6379/0
#       - DEBUG=True
#       - DJANGO_SECRET_KEY=devkey

#   redis:
#     image: redis:7
#     ports:
#       - "6379:6379"

#   celery:
#     build: .
#     command: celery -A ecommerce_api worker -l info
#     volumes:
#       - .:/app
#     depends_on:
#       - redis
#     environment:
#       - CELERY_BROKER_URL=redis://redis:6379/0

#   beat:
#     build:
#       context: .
#     command: celery -A ecommerce_api beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
#     volumes:
#       - .:/app
#     depends_on:
#       - web
#       - redis
#     environment:
#       - CELERY_BROKER_URL=redis://redis:6379/0

#   db:
#     image: postgres:15
#     restart: always
#     environment:
#       POSTGRES_DB: ecommerce
#       POSTGRES_USER: myuser
#       POSTGRES_PASSWORD: mypass
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
