/* tslint:disable */
/* eslint-disable */
/**
 * ECOMMERCE-API
 * REST API for managing products, orders, order items, user accounts and authentication 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: joachimtramper@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Address
 */
export interface Address {
    /**
     * 
     * @type {number}
     * @memberof Address
     */
    'id': number;
    /**
     * e.g. \'Home\', \'Work\'
     * @type {string}
     * @memberof Address
     */
    'label': string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'street': string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'number': string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'zipcode': string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'city': string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    'country': string;
    /**
     * 
     * @type {boolean}
     * @memberof Address
     */
    'is_billing'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Address
     */
    'is_shipping'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Address
     */
    'profile': number;
}

