/* tslint:disable */
/* eslint-disable */
/**
 * ECOMMERCE-API
 * REST API for managing products, orders, order items, user accounts and authentication 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: joachimtramper@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OrderItemDetail } from './order-item-detail';

/**
 * 
 * @export
 * @interface Cart
 */
export interface Cart {
    /**
     * 
     * @type {string}
     * @memberof Cart
     */
    'order_id': string;
    /**
     * 
     * @type {string}
     * @memberof Cart
     */
    'created_at': string;
    /**
     * 
     * @type {Array<OrderItemDetail>}
     * @memberof Cart
     */
    'items': Array<OrderItemDetail>;
    /**
     * 
     * @type {number}
     * @memberof Cart
     */
    'total_amount': number;
}

