/* tslint:disable */
/* eslint-disable */
/**
 * ECOMMERCE-API
 * REST API for managing products, orders, order items, user accounts and authentication 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: joachimtramper@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CustomerProfile
 */
export interface CustomerProfile {
    /**
     * 
     * @type {number}
     * @memberof CustomerProfile
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof CustomerProfile
     */
    'phone_number'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerProfile
     */
    'date_of_birth'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CustomerProfile
     */
    'user': number;
}

