/* tslint:disable */
/* eslint-disable */
/**
 * ECOMMERCE-API
 * REST API for managing products, orders, order items, user accounts and authentication 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: joachimtramper@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OrderItemCreateUpdate
 */
export interface OrderItemCreateUpdate {
    /**
     * 
     * @type {number}
     * @memberof OrderItemCreateUpdate
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof OrderItemCreateUpdate
     */
    'order': string;
    /**
     * 
     * @type {number}
     * @memberof OrderItemCreateUpdate
     */
    'product': number;
    /**
     * 
     * @type {number}
     * @memberof OrderItemCreateUpdate
     */
    'quantity': number;
    /**
     * 
     * @type {number}
     * @memberof OrderItemCreateUpdate
     */
    'item_subtotal': number;
}

