/* tslint:disable */
/* eslint-disable */
/**
 * ECOMMERCE-API
 * REST API for managing products, orders, order items, user accounts and authentication 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: joachimtramper@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OrderItemDetail } from './order-item-detail';
// May contain unused imports in some cases
// @ts-ignore
import type { StatusEnum } from './status-enum';

/**
 * 
 * @export
 * @interface OrderCreate
 */
export interface OrderCreate {
    /**
     * 
     * @type {string}
     * @memberof OrderCreate
     */
    'order_id': string;
    /**
     * 
     * @type {StatusEnum}
     * @memberof OrderCreate
     */
    'status'?: StatusEnum;
    /**
     * 
     * @type {Array<OrderItemDetail>}
     * @memberof OrderCreate
     */
    'items': Array<OrderItemDetail>;
}



