/* tslint:disable */
/* eslint-disable */
/**
 * ECOMMERCE-API
 * REST API for managing products, orders, order items, user accounts and authentication 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: joachimtramper@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Product } from './product';

/**
 * 
 * @export
 * @interface OrderItemDetail
 */
export interface OrderItemDetail {
    /**
     * 
     * @type {number}
     * @memberof OrderItemDetail
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof OrderItemDetail
     */
    'order': string;
    /**
     * 
     * @type {Product}
     * @memberof OrderItemDetail
     */
    'product': Product;
    /**
     * 
     * @type {number}
     * @memberof OrderItemDetail
     */
    'product_id': number;
    /**
     * 
     * @type {number}
     * @memberof OrderItemDetail
     */
    'quantity': number;
    /**
     * 
     * @type {number}
     * @memberof OrderItemDetail
     */
    'item_subtotal': number;
}

