/* tslint:disable */
/* eslint-disable */
/**
 * ECOMMERCE-API
 * REST API for managing products, orders, order items, user accounts and authentication 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: joachimtramper@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OrderCreate } from './order-create';

/**
 * 
 * @export
 * @interface PaginatedOrderCreateList
 */
export interface PaginatedOrderCreateList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedOrderCreateList
     */
    'count': number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedOrderCreateList
     */
    'next'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedOrderCreateList
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<OrderCreate>}
     * @memberof PaginatedOrderCreateList
     */
    'results': Array<OrderCreate>;
}

