/* tslint:disable */
/* eslint-disable */
/**
 * ECOMMERCE-API
 * REST API for managing products, orders, order items, user accounts and authentication 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: joachimtramper@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PatchedAddress
 */
export interface PatchedAddress {
    /**
     * 
     * @type {number}
     * @memberof PatchedAddress
     */
    'id'?: number;
    /**
     * e.g. \'Home\', \'Work\'
     * @type {string}
     * @memberof PatchedAddress
     */
    'label'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedAddress
     */
    'street'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedAddress
     */
    'number'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedAddress
     */
    'zipcode'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedAddress
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedAddress
     */
    'country'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedAddress
     */
    'is_billing'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedAddress
     */
    'is_shipping'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PatchedAddress
     */
    'profile'?: number;
}

