/* tslint:disable */
/* eslint-disable */
/**
 * ECOMMERCE-API
 * REST API for managing products, orders, order items, user accounts and authentication 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: joachimtramper@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PatchedProduct
 */
export interface PatchedProduct {
    /**
     * 
     * @type {number}
     * @memberof PatchedProduct
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedProduct
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedProduct
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedProduct
     */
    'price'?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedProduct
     */
    'stock'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedProduct
     */
    'in_stock'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PatchedProduct
     */
    'image'?: string | null;
}

