/* tslint:disable */
/* eslint-disable */
/**
 * ECOMMERCE-API
 * REST API for managing products, orders, order items, user accounts and authentication 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: joachimtramper@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Product
 */
export interface Product {
    /**
     * 
     * @type {number}
     * @memberof Product
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    'price': string;
    /**
     * 
     * @type {number}
     * @memberof Product
     */
    'stock': number;
    /**
     * 
     * @type {boolean}
     * @memberof Product
     */
    'in_stock': boolean;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    'image'?: string | null;
}

