@base_url = http://localhost:8000/api
@ACCESS =
@REFRESH =

### Login (obtain JWT)

POST {{base_url}}/token/
Content-Type: application/json

{
  "email": "mirandadennis@example.com",
  "password": "yjffdaMUWuCl"
}

# > {% client.global.set("ACCESS", response.body.access) %}
# > {% client.global.set("REFRESH", response.body.refresh) %}
# # > {% client.log("REFRESH: " + response.body.refresh) %}

### Refresh token
POST {{base_url}}/token/refresh/
Content-Type: application/json

{"refresh": "{{REFRESH}}"}


### List products
GET {{base_url}}/shop/products/
Authorization: Bearer {{ACCESS}}

> {% client.log("Statuscode: " + response.status) %}

### Retrieve a single product
GET {{base_url}}/shop/products/1/
Authorization: Bearer {{ACCESS}}

### Create a product
POST {{base_url}}/shop/products/
Content-Type: application/json
Authorization: Bearer {{ACCESS}}

{
  "name": "Eco Widget",
  "description": "A sustainable widget for everyday use.",
  "price": "19.99",
  "stock": 100
}

### Update a product
PUT {{base_url}}/shop/products/1/
Content-Type: application/json
Authorization: Bearer {{ACCESS}}

{
  "name": "Eco Widget Plus",
  "description": "An improved sustainable widget.",
  "price": "24.99",
  "stock": 80
}

### Patch a product
PATCH {{base_url}}/shop/products/1/
Content-Type: application/json
Authorization: Bearer {{ACCESS}}

{
  "price": "54.99"
}

### Delete a product
DELETE {{base_url}}/shop/products/52/
Authorization: Bearer {{ACCESS}}

### ORDERS -----------------------------------------------------------------------------------

### List orders
GET {{base_url}}/shop/orders/
Authorization: Bearer {{ACCESS}}

### Retrieve a single order
GET {{base_url}}/shop/orders/31153702-f8f4-4007-8192-6ca96bf7b15a/
Authorization: Bearer {{ACCESS}}

### Create an order
POST {{base_url}}/shop/orders/
Content-Type: application/json
Authorization: Bearer {{ACCESS}}

{
  "items": [
    {"product_id": 1, "quantity": 2},
    {"product_id": 3, "quantity": 1}
  ]
}

### Update an order
PUT {{base_url}}/shop/orders/8c3dda32-ce89-48ff-88d6-18079e8895ef/
Content-Type: application/json
Authorization: Bearer {{ACCESS}}

{
  "status": "Pending",
  "items": [
    { "product_id": 1, "quantity": 3 }
  ]
}

### PATCH an order
PATCH {{base_url}}/shop/orders/8c3dda32-ce89-48ff-88d6-18079e8895ef/
Content-Type: application/json
Authorization: Bearer {{ACCESS}}

{
  "status": "Shipped"
}

### Delete an order
DELETE {{base_url}}/shop/orders/8c3dda32-ce89-48ff-88d6-18079e8895ef/
Authorization: Bearer {{ACCESS}}

### ORDER ITEMS -----------------------------------------------------------------------------------

### List order-items
GET {{base_url}}/shop/order-items/
Authorization: Bearer {{ACCESS}}

### Retrieve a single order-item
GET {{base_url}}/shop/order-items/621/
Authorization: Bearer {{ACCESS}}

### Create an order-item
POST {{base_url}}/shop/order-items/
Content-Type: application/json
Authorization: Bearer {{ACCESS}}

{
  "order": "8c3dda32-ce89-48ff-88d6-18079e8895ef",
  "product_id": 8,
  "quantity": 5
}

### Update an order-item
PUT {{base_url}}/shop/order-items/622/
Content-Type: application/json
Authorization: Bearer {{ACCESS}}

{
  "order": "8c3dda32-ce89-48ff-88d6-18079e8895ef",
  "product_id": 4,
  "quantity": 3
}

### PATCH an order-item
PATCH {{base_url}}/shop/order-items/622/
Content-Type: application/json
Authorization: Bearer {{ACCESS}}

{
  "quantity": 10
}

### Delete an order-item
DELETE {{base_url}}/shop/order-items/621/
Authorization: Bearer {{ACCESS}}

### Debug time
GET https://jsonplaceholder.typicode.com/todos/1

> {% client.log("🛠  Hello from REST Client!") %}
