# Generated by Django 5.2 on 2025-05-05 08:50

from decimal import Decimal

from django.db import migrations, models


def populate_orderitem_price(apps, schema_editor):
    OrderItem = apps.get_model("shop", "OrderItem")
    Product = apps.get_model("shop", "Product")

    for item in OrderItem.objects.all():
        # pak de huidige prijs uit het Product
        product = Product.objects.get(pk=item.product_id)
        item.price = product.price
        item.save(update_fields=["price"])


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_alter_order_options_alter_orderitem_options_and_more"),
    ]

    operations = [
        migrations.RunPython(
            populate_orderitem_price, reverse_code=migrations.RunPython.noop
        ),
    ]
