# Generated by Django 5.2 on 2025-05-10 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_auto_20250505_1550"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "Pending")),
                fields=("user",),
                name="unique_pending_order_per_user",
            ),
        ),
    ]
