# Generated by Django 5.2 on 2025-06-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0007_order_unique_pending_order_per_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="reserved_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("AwaitingPayment", "Awaiting Payment"),
                    ("Confirmed", "Confirmed"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
