# Generated by Django 5.2 on 2025-06-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0008_order_reserved_until_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock_reserved",
            field=models.IntegerField(default=0),
        ),
    ]
